import type { GoalDefinition } from './types'

export const GOAL_ALBUM_ID = 'world-cup-2026'

export const goalDefinitions: GoalDefinition[] = [
  {
    id: 'buy-first-pack',
    category: 'packs',
    title: 'Купить первый набор',
    description: 'Купи набор карточек в магазине.',
    order: 10,
    requirements: [{ type: 'packs-purchased', target: 1 }],
    reward: [{ type: 'coins', amount: 10 }],
    action: { label: 'В магазин', route: { name: 'shop' } },
  },
  {
    id: 'open-first-pack',
    category: 'packs',
    title: 'Открыть первый набор',
    description: 'Открой набор и познакомься с его карточками.',
    order: 20,
    requirements: [{ type: 'packs-opened', target: 1 }],
    reward: [{ type: 'coins', amount: 15 }],
    action: { label: 'Открыть набор', route: { name: 'pack-opening' } },
  },
  {
    id: 'open-5-packs',
    category: 'packs',
    title: 'Открыть 5 наборов',
    description: 'Продолжай пополнять коллекцию.',
    order: 30,
    requirements: [
      { type: 'goal-completed', goalId: 'open-first-pack' },
      { type: 'packs-opened', target: 5 },
    ],
    reward: [{ type: 'energy', amount: 25 }],
    action: { label: 'К наборам', route: { name: 'shop' } },
  },
  {
    id: 'open-15-packs',
    category: 'packs',
    title: 'Открыть 15 наборов',
    description: 'Собери серьёзную серию открытий.',
    order: 40,
    requirements: [
      { type: 'goal-completed', goalId: 'open-5-packs' },
      { type: 'packs-opened', target: 15 },
    ],
    reward: [{ type: 'pack', packId: 'standard', amount: 1 }],
    action: { label: 'К наборам', route: { name: 'shop' } },
  },
  {
    id: 'collect-10-unique',
    category: 'collection',
    title: 'Собрать 10 уникальных карточек',
    description: 'Найди десять разных позиций журнала.',
    order: 50,
    requirements: [{ type: 'unique-cards-collected', target: 10 }],
    reward: [{ type: 'coins', amount: 25 }],
    action: { label: 'Коллекция', route: { name: 'collection' } },
  },
  {
    id: 'collect-25-unique',
    category: 'collection',
    title: 'Собрать 25 уникальных карточек',
    description: 'Расширь коллекцию до двадцати пяти позиций.',
    order: 60,
    requirements: [
      { type: 'goal-completed', goalId: 'collect-10-unique' },
      { type: 'unique-cards-collected', target: 25 },
    ],
    reward: [{ type: 'coins', amount: 50 }],
    action: { label: 'Коллекция', route: { name: 'collection' } },
  },
  {
    id: 'collect-first-rare',
    category: 'collection',
    title: 'Найти первую редкую карточку',
    description: 'Получи карточку редкости rare.',
    order: 70,
    requirements: [{ type: 'rarity-collected', rarity: 'rare', target: 1 }],
    reward: [{ type: 'energy', amount: 15 }],
    action: { label: 'Коллекция', route: { name: 'collection' } },
  },
  {
    id: 'collect-first-variant',
    category: 'collection',
    title: 'Найти первую альтернативную версию',
    description: 'Получи особую версию существующей карточки.',
    order: 80,
    requirements: [{ type: 'variant-collected', target: 1 }],
    reward: [{ type: 'coins', amount: 75 }],
    action: { label: 'Коллекция', route: { name: 'collection' } },
  },
  {
    id: 'prepare-first-sticker',
    category: 'album',
    title: 'Подготовить первую наклейку',
    description: 'Сними защитный слой и подготовь карточку к вклейке.',
    order: 90,
    requirements: [{ type: 'stickers-prepared', target: 1 }],
    reward: [{ type: 'coins', amount: 15 }],
    action: { label: 'Выбрать карточку', route: { name: 'collection' } },
  },
  {
    id: 'place-first-sticker',
    category: 'album',
    title: 'Вклеить первую наклейку',
    description: 'Размести подготовленную карточку в журнале.',
    order: 100,
    requirements: [{ type: 'stickers-placed', target: 1 }],
    reward: [{ type: 'energy', amount: 15 }],
    action: { label: 'Открыть журнал', route: { name: 'album-wc-26' } },
  },
  {
    id: 'place-10-stickers',
    category: 'album',
    title: 'Вклеить 10 наклеек',
    description: 'Заполни десять уникальных слотов журнала.',
    order: 110,
    requirements: [
      { type: 'goal-completed', goalId: 'place-first-sticker' },
      { type: 'album-slots-filled', albumId: GOAL_ALBUM_ID, target: 10 },
    ],
    reward: [{ type: 'coins', amount: 50 }],
    action: { label: 'Открыть журнал', route: { name: 'album-wc-26' } },
  },
  {
    id: 'fill-first-page',
    category: 'album',
    title: 'Заполнить первую страницу',
    description: 'Заполни все десять слотов первой игровой страницы.',
    order: 120,
    requirements: [
      {
        type: 'album-page-filled',
        albumId: GOAL_ALBUM_ID,
        pageId: 'mexico-left',
        target: 10,
      },
    ],
    reward: [{ type: 'pack', packId: 'standard', amount: 1 }],
    action: { label: 'Открыть страницу', route: { name: 'album-wc-26' } },
  },
  {
    id: 'reach-album-10-percent',
    category: 'album',
    title: 'Заполнить журнал на 10%',
    description: 'Займи десятую часть всех слотов журнала.',
    order: 130,
    requirements: [
      { type: 'album-progress', albumId: GOAL_ALBUM_ID, targetPercent: 10 },
    ],
    reward: [{ type: 'coins', amount: 100 }],
    action: { label: 'Открыть журнал', route: { name: 'album-wc-26' } },
  },
  {
    id: 'complete-first-minigame',
    category: 'minigames',
    title: 'Завершить первую мини-игру',
    description: 'Пройди мини-игру и забери бесплатный набор.',
    order: 140,
    requirements: [{ type: 'minigames-completed', target: 1 }],
    reward: [{ type: 'coins', amount: 20 }],
    action: { label: 'Сыграть', route: { name: 'pack-hunt' } },
  },
  {
    id: 'complete-5-minigames',
    category: 'minigames',
    title: 'Завершить 5 мини-игр',
    description: 'Пройди пять мини-игр.',
    order: 150,
    requirements: [
      { type: 'goal-completed', goalId: 'complete-first-minigame' },
      { type: 'minigames-completed', target: 5 },
    ],
    reward: [{ type: 'pack', packId: 'standard', amount: 1 }],
    action: { label: 'Сыграть', route: { name: 'pack-hunt' } },
  },
  {
    id: 'exchange-first-duplicates',
    category: 'collection',
    title: 'Обменять повторки',
    description: 'Заверши первый обмен повторных карточек.',
    order: 160,
    requirements: [{ type: 'duplicates-exchanged', target: 1 }],
    reward: [{ type: 'coins', amount: 40 }],
    action: {
      label: 'К повторкам',
      route: { name: 'collection', query: { tab: 'duplicates' } },
    },
  },
]
