import type { GoalDefinition } from './types'

export const GOAL_ALBUM_ID = 'world-cup-2026'

export const goalDefinitions: GoalDefinition[] = [
  {
    id: 'buy-first-pack',
    category: 'packs',
    titleKey: 'goals.items.buyFirstPack.title',
    descriptionKey: 'goals.items.buyFirstPack.description',
    order: 10,
    requirements: [{ type: 'packs-purchased', target: 1 }],
    reward: [{ type: 'coins', amount: 10 }],
    action: { labelKey: 'goals.items.buyFirstPack.action', route: { name: 'shop' } },
  },
  {
    id: 'open-first-pack',
    category: 'packs',
    titleKey: 'goals.items.openFirstPack.title',
    descriptionKey: 'goals.items.openFirstPack.description',
    order: 20,
    requirements: [{ type: 'packs-opened', target: 1 }],
    reward: [{ type: 'coins', amount: 15 }],
    action: { labelKey: 'goals.items.openFirstPack.action', route: { name: 'pack-opening' } },
  },
  {
    id: 'open-5-packs',
    category: 'packs',
    titleKey: 'goals.items.open5Packs.title',
    descriptionKey: 'goals.items.open5Packs.description',
    order: 30,
    requirements: [
      { type: 'goal-completed', goalId: 'open-first-pack' },
      { type: 'packs-opened', target: 5 },
    ],
    reward: [{ type: 'energy', amount: 25 }],
    action: { labelKey: 'goals.items.open5Packs.action', route: { name: 'shop' } },
  },
  {
    id: 'open-15-packs',
    category: 'packs',
    titleKey: 'goals.items.open15Packs.title',
    descriptionKey: 'goals.items.open15Packs.description',
    order: 40,
    requirements: [
      { type: 'goal-completed', goalId: 'open-5-packs' },
      { type: 'packs-opened', target: 15 },
    ],
    reward: [{ type: 'pack', packId: 'standard', amount: 1 }],
    action: { labelKey: 'goals.items.open15Packs.action', route: { name: 'shop' } },
  },
  {
    id: 'collect-10-unique',
    category: 'collection',
    titleKey: 'goals.items.collect10Unique.title',
    descriptionKey: 'goals.items.collect10Unique.description',
    order: 50,
    requirements: [{ type: 'unique-cards-collected', target: 10 }],
    reward: [{ type: 'coins', amount: 25 }],
    action: { labelKey: 'goals.items.collect10Unique.action', route: { name: 'collection' } },
  },
  {
    id: 'collect-25-unique',
    category: 'collection',
    titleKey: 'goals.items.collect25Unique.title',
    descriptionKey: 'goals.items.collect25Unique.description',
    order: 60,
    requirements: [
      { type: 'goal-completed', goalId: 'collect-10-unique' },
      { type: 'unique-cards-collected', target: 25 },
    ],
    reward: [{ type: 'coins', amount: 50 }],
    action: { labelKey: 'goals.items.collect25Unique.action', route: { name: 'collection' } },
  },
  {
    id: 'collect-first-rare',
    category: 'collection',
    titleKey: 'goals.items.collectFirstRare.title',
    descriptionKey: 'goals.items.collectFirstRare.description',
    order: 70,
    requirements: [{ type: 'rarity-collected', rarity: 'rare', target: 1 }],
    reward: [{ type: 'energy', amount: 15 }],
    action: { labelKey: 'goals.items.collectFirstRare.action', route: { name: 'collection' } },
  },
  {
    id: 'collect-first-variant',
    category: 'collection',
    titleKey: 'goals.items.collectFirstVariant.title',
    descriptionKey: 'goals.items.collectFirstVariant.description',
    order: 80,
    requirements: [{ type: 'variant-collected', target: 1 }],
    reward: [{ type: 'coins', amount: 75 }],
    action: { labelKey: 'goals.items.collectFirstVariant.action', route: { name: 'collection' } },
  },
  {
    id: 'prepare-first-sticker',
    category: 'album',
    titleKey: 'goals.items.prepareFirstSticker.title',
    descriptionKey: 'goals.items.prepareFirstSticker.description',
    order: 90,
    requirements: [{ type: 'stickers-prepared', target: 1 }],
    reward: [{ type: 'coins', amount: 15 }],
    action: { labelKey: 'goals.items.prepareFirstSticker.action', route: { name: 'collection' } },
  },
  {
    id: 'place-first-sticker',
    category: 'album',
    titleKey: 'goals.items.placeFirstSticker.title',
    descriptionKey: 'goals.items.placeFirstSticker.description',
    order: 100,
    requirements: [{ type: 'stickers-placed', target: 1 }],
    reward: [{ type: 'energy', amount: 15 }],
    action: { labelKey: 'goals.items.placeFirstSticker.action', route: { name: 'album-detail', params: { albumId: 'wc-26' } } },
  },
  {
    id: 'place-10-stickers',
    category: 'album',
    titleKey: 'goals.items.place10Stickers.title',
    descriptionKey: 'goals.items.place10Stickers.description',
    order: 110,
    requirements: [
      { type: 'goal-completed', goalId: 'place-first-sticker' },
      { type: 'album-slots-filled', albumId: GOAL_ALBUM_ID, target: 10 },
    ],
    reward: [{ type: 'coins', amount: 50 }],
    action: { labelKey: 'goals.items.place10Stickers.action', route: { name: 'album-detail', params: { albumId: 'wc-26' } } },
  },
  {
    id: 'fill-first-page',
    category: 'album',
    titleKey: 'goals.items.fillFirstPage.title',
    descriptionKey: 'goals.items.fillFirstPage.description',
    order: 120,
    requirements: [
      {
        type: 'album-pages-completed',
        albumId: GOAL_ALBUM_ID,
        target: 1,
      },
    ],
    reward: [{ type: 'pack', packId: 'standard', amount: 1 }],
    action: { labelKey: 'goals.items.fillFirstPage.action', route: { name: 'album-detail', params: { albumId: 'wc-26' } } },
  },
  {
    id: 'complete-first-team',
    category: 'album',
    titleKey: 'goals.items.completeFirstTeam.title',
    descriptionKey: 'goals.items.completeFirstTeam.description',
    order: 121,
    requirements: [
      { type: 'goal-completed', goalId: 'fill-first-page' },
      { type: 'album-teams-completed', albumId: GOAL_ALBUM_ID, target: 1 },
    ],
    reward: [{ type: 'coins', amount: 100 }],
    action: { labelKey: 'goals.items.completeFirstTeam.action', route: { name: 'album-detail', params: { albumId: 'wc-26' } } },
  },
  {
    id: 'complete-4-teams',
    category: 'album',
    titleKey: 'goals.items.complete4Teams.title',
    descriptionKey: 'goals.items.complete4Teams.description',
    order: 122,
    requirements: [
      { type: 'goal-completed', goalId: 'complete-first-team' },
      { type: 'album-teams-completed', albumId: GOAL_ALBUM_ID, target: 4 },
    ],
    reward: [{ type: 'pack', packId: 'standard', amount: 1 }],
    action: { labelKey: 'goals.items.complete4Teams.action', route: { name: 'album-detail', params: { albumId: 'wc-26' } } },
  },
  {
    id: 'complete-12-teams',
    category: 'album',
    titleKey: 'goals.items.complete12Teams.title',
    descriptionKey: 'goals.items.complete12Teams.description',
    order: 123,
    requirements: [
      { type: 'goal-completed', goalId: 'complete-4-teams' },
      { type: 'album-teams-completed', albumId: GOAL_ALBUM_ID, target: 12 },
    ],
    reward: [{ type: 'pack', packId: 'standard', amount: 3 }],
    action: { labelKey: 'goals.items.complete12Teams.action', route: { name: 'album-detail', params: { albumId: 'wc-26' } } },
  },
  {
    id: 'reach-album-10-percent',
    category: 'album',
    titleKey: 'goals.items.reachAlbum10Percent.title',
    descriptionKey: 'goals.items.reachAlbum10Percent.description',
    order: 130,
    requirements: [
      { type: 'album-progress', albumId: GOAL_ALBUM_ID, targetPercent: 10 },
    ],
    reward: [{ type: 'coins', amount: 100 }],
    action: { labelKey: 'goals.items.reachAlbum10Percent.action', route: { name: 'album-detail', params: { albumId: 'wc-26' } } },
  },
  {
    id: 'complete-first-minigame',
    category: 'minigames',
    titleKey: 'goals.items.completeFirstMinigame.title',
    descriptionKey: 'goals.items.completeFirstMinigame.description',
    order: 140,
    requirements: [{ type: 'minigames-completed', target: 1 }],
    reward: [{ type: 'coins', amount: 20 }],
    action: { labelKey: 'goals.items.completeFirstMinigame.action', route: { name: 'pack-hunt' } },
  },
  {
    id: 'complete-5-minigames',
    category: 'minigames',
    titleKey: 'goals.items.complete5Minigames.title',
    descriptionKey: 'goals.items.complete5Minigames.description',
    order: 150,
    requirements: [
      { type: 'goal-completed', goalId: 'complete-first-minigame' },
      { type: 'minigames-completed', target: 5 },
    ],
    reward: [{ type: 'pack', packId: 'standard', amount: 1 }],
    action: { labelKey: 'goals.items.complete5Minigames.action', route: { name: 'pack-hunt' } },
  },
  {
    id: 'exchange-first-duplicates',
    category: 'collection',
    titleKey: 'goals.items.exchangeFirstDuplicates.title',
    descriptionKey: 'goals.items.exchangeFirstDuplicates.description',
    order: 160,
    requirements: [{ type: 'duplicates-exchanged', target: 1 }],
    reward: [{ type: 'coins', amount: 40 }],
    action: {
      labelKey: 'goals.items.exchangeFirstDuplicates.action',
      route: { name: 'collection', query: { tab: 'duplicates' } },
    },
  },
]
