import { FREE_PACK_COOLDOWN_MS } from '@/config/gameBalance'

/** Общие и индивидуальные параметры мини-игр, выдающих бесплатный пак. */
export const PACK_HUNT_CONFIG = {
  cooldownMs: FREE_PACK_COOLDOWN_MS,
  games: [
    { id: 'signal', weight: 1 },
    { id: 'rack', weight: 1 },
    { id: 'machine', weight: 1 },
    { id: 'shell', weight: 1 },
    { id: 'puzzle', weight: 1 },
    { id: 'catch', weight: 1 },
    { id: 'memory', weight: 1 },
    { id: 'passCombo', weight: 1 },
  ],
  signalsRequired: 3,
  holdDurationMs: 3_000,
  signalTransitionMs: 500,
  signalCompletionDelayMs: 650,
  detectionRadiusPercent: 11,
  mediumSignalRadiusPercent: 23,
  weakSignalRadiusPercent: 40,
  minimumTargetDistancePercent: 38,
  targetPaddingPercent: 16,
  scannerPaddingPercent: 4,
  keyboardStepPercent: 4,
  targetCandidateAttempts: 40,
  maxFrameDeltaMs: 64,
  lockDecayPercent: 35,
  rack: {
    minimumDurationMs: 10_000,
    stageTransitionMs: 450,
    stackSeparationPercent: 4,
    spreadTargetPercent: 24,
    gripDurationMs: 3_500,
    pathTolerancePercent: 10,
    maxFrameDeltaMs: 64,
    gripDecayPercent: 30,
    route: {
      pointCountMin: 5,
      pointCountMax: 7,
      xMinPercent: 12,
      xMaxPercent: 88,
      yMinPercent: 12,
      yMaxPercent: 88,
      startYMinPercent: 72,
      startYMaxPercent: 88,
      endYMinPercent: 12,
      endYMaxPercent: 28,
      minimumSegmentLengthPercent: 24,
      minimumPointSpacingPercent: 13,
      minimumHorizontalChangePercent: 14,
      candidateAttempts: 80,
    },
  },
  machine: {
    minimumDurationMs: 10_000,
    stageTransitionMs: 450,
    drumOffsetMinPercent: 28,
    drumOffsetMaxPercent: 38,
    drumAlignmentTolerancePercent: 5,
    timingCycleMs: 1_800,
    timingTargetCenterPercent: 54,
    timingTargetWidthPercent: 24,
    pathTolerancePercent: 10,
    pointerClickSuppressionMs: 700,
    route: {
      pointCountMin: 5,
      pointCountMax: 7,
      xMinPercent: 12,
      xMaxPercent: 88,
      yMinPercent: 10,
      yMaxPercent: 90,
      startYMinPercent: 10,
      startYMaxPercent: 24,
      endYMinPercent: 76,
      endYMaxPercent: 90,
      minimumSegmentLengthPercent: 24,
      minimumPointSpacingPercent: 13,
      minimumHorizontalChangePercent: 14,
      candidateAttempts: 80,
    },
  },
  shell: {
    rounds: [
      { boxCount: 3, swapCount: 3, swapDurationMs: 950, feintChance: 0 },
      { boxCount: 3, swapCount: 5, swapDurationMs: 650, feintChance: 0.25 },
      { boxCount: 4, swapCount: 6, swapDurationMs: 600, feintChance: 0.2 },
    ],
    revealDurationMs: 1_500,
    preShuffleDelayMs: 500,
    firstMoveExtraMs: 380,
    resultDelayMs: 1_100,
    completionDelayMs: 900,
    feintPauseMs: 200,
    feintPeakFraction: 0.55,
    fieldPaddingPercent: 15,
    elapsedIntervalMs: 1_000,
  },
  puzzle: {
    fragmentCountMin: 4,
    fragmentCountMax: 6,
    cardAspectRatio: 0.7142857,
    lowWeightBiasPower: 2,
    completionDelayMs: 900,
    wrongSlotFeedbackMs: 1_000,
  },
  catch: {
    sessionDurationSeconds: 18,
    completionDelayMs: 1_300,
    catcherWidthPercent: 16,
    catchLinePercent: 82,
    catchBandHalfPercent: 4,
    catchToleranceExtraPercent: 3,
    keyboardMovePercentPerSecond: 85,
    stumbleDurationMs: 1_100,
    stumbleSpeedMultiplier: 0.45,
    spawnIntervalStartMs: 950,
    spawnIntervalEndMs: 480,
    fallDurationStartMs: 3_600,
    fallDurationEndMs: 2_100,
    fallDurationJitterMin: 0.85,
    fallDurationJitterMax: 1.15,
    obstacleWeightStart: 0.08,
    obstacleWeightEnd: 0.24,
    goldenWeightStart: 0.12,
    goldenWeightEnd: 0.16,
    emptyWeight: 0.16,
    packScore: 1,
    goldenScore: 5,
    obstacleScore: -3,
    floatingLabelLifetimeMs: 700,
    initialCatcherXPercent: 50,
    initialItemYPercent: -6,
    itemDespawnYPercent: 104,
    maxFrameDeltaMs: 48,
  },
  memory: {
    roundsCount: 3,
    cardsPerRarity: 2,
    revealDurationMs: 3_200,
    flipDurationMs: 500,
    answerEnableExtraDelayMs: 150,
    resultDelayMs: 1_800,
    completionDelayMs: 1_000,
  },
  passCombo: {
    positions: [
      { key: 'leftBack', xPercent: 22, yPercent: 80 },
      { key: 'center', xPercent: 50, yPercent: 54 },
      { key: 'rightWinger', xPercent: 80, yPercent: 30 },
      { key: 'striker', xPercent: 50, yPercent: 12 },
    ] as const,
    roundLengths: [3, 4, 5] as const,
    highlightOnMs: 550,
    highlightGapMs: 260,
    sequenceStartDelayMs: 500,
    mistakeFlashMs: 260,
    mistakeReplayDelayMs: 900,
    roundResultDelayMs: 1_300,
    completionDelayMs: 1_000,
    fastThresholdMs: 900,
    threeStarMaximumMistakes: 0,
    twoStarMaximumMistakes: 2,
  },
}

/** Полный размер координатного поля мини-игр в процентах. */
export const MINI_GAME_FIELD_PERCENT: number = 100
